name: "Run unit tests"
on:
  push:

jobs:
  qc-and-test:
    name: "QC and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Cache dataset
        id: kaggle-dataset
        uses: actions/cache@v4
        with:
          path: ./data
          key: kaggle-dataset
      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          rm requirements*.txt || echo "No stored requirements"
          make install-all

          mkdir -p ~/.kaggle
          echo '${{secrets.KAGGLE_JSON}}' >> ~/.kaggle/kaggle.json
          chmod 600 /home/runner/.kaggle/kaggle.json

          make dataset

      - name: Unit tests [pytest]
        run: |
          pytest --cov=geolife_clef_2024 --cov-report term-missing
          coverage report --format=markdown -m >> $GITHUB_STEP_SUMMARY

      - name: QC [ruff]
        if: ${{!cancelled()}}
        run: ruff check geolife_clef_2024
