name: "Run unit tests"
on:
  push:

jobs:
  qc-and-test:
    name: "QC and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          make install-all
          make dataset
      - name: Cache dataset
        id: kaggle-dataset
        uses: actions/cache@v4
        with:
          path: ./data
          key: kaggle-dataset
      - name: Unit tests [pytest]
        run: |
          pytest --cov=geolife_clef_2024 --cov-report term-missing
          coverage report --format=markdown -m >> $GITHUB_STEP_SUMMARY

      - name: QC [ruff]
        if: ${{!cancelled()}}
        run: ruff check geolife_clef_2024
